name: Rule Provider

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: rule providers
        working-directory: ./set_rule
        run: |
          echo "Downloading basicads source list..."
          curl -s https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml -o ./ADSblocks/basicads.yaml
          rm -fr ./ADSblocks/basicads.yamle

          echo "Downloading advertising source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising.yaml -o ./ADSblocks/ads.yaml
          rm -fr ./ADSblocks/ads.yamle
          
          echo "Downloading nsfw source list..."
          curl -s https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_nsfw.yaml -o ./NSFW/nsfw.yaml
          rm -fr ./NSFW/nsfw.yamle

          echo "Downloading maliciuos source list..."
          curl -s https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_maliciousip.yaml -o ./Malicious/maliciousip.yaml
          rm -fr ./Malicious/maliciousip.yamle

          echo "Downloading malicious source list..."
          curl -s https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_malicious.yaml -o ./Malicious/malicious.yaml
          rm -fr ./Malicious/malicious.yamle

          echo "Downloading hijacking source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Hijacking/Hijacking.yaml -o ./Hijack/hijacking.yaml
          rm -fr ./Hijack/hijacking.yamle

          echo "Downloading privacy source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml -o ./Tracker/tracker.yaml
          rm -fr ./Tracker/tracker.yamle

          echo "Downloading privacy source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/EasyPrivacy/EasyPrivacy.yaml -o ./EasyPrivacy/easyprivacy.yaml
          rm -fr ./EasyPrivacy/easyprivacy.yamle

          echo "Downloading porn source list..."
          curl -s https://rules.kr328.app/category-porn.yaml -o ./NSFW/porn.yaml
          rm -fr ./NSFW/porn.yamle

          echo "Downloading lancidr source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml -o ./LAN/LAN.yaml
          rm -fr ./LAN/LAN.yamle

          echo "Downloading telegram source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml -o ./Telegram/telegram.yaml
          rm -fr ./Telegram/telegram.yamle

          echo "Downloading games source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml -o ./Games/games.yaml
          rm -fr ./Games/games.yamle

          echo "Downloading line source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Line/Line.yaml -o ./Line/line.yaml
          rm -fr ./Line/line.yamle

          echo "Downloading facebok source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Facebook/Facebook.yaml -o ./Facebook/facebook.yaml
          rm -fr ./Facebook/facebook.yamle

          echo "Downloading whatsapp source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Whatsapp/Whatsapp.yaml -o ./Whatsapp/whatsapp.yaml
          rm -fr ./Whatsapp/whatsapp.yamle

          echo "Downloading tiktok source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml -o ./Tiktok/tiktok.yaml
          rm -fr ./Tiktok/tiktok.yamle

          echo "Downloading Instagram source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Instagram/Instagram.yaml -o ./Instagram/instagram.yaml
          rm -fr ./Instagram/instagram.yamle

          echo "Downloading Twitter source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml -o ./Twitter/twitter.yaml
          rm -fr ./Twitter/twitter.yamle

          echo "Downloading Twitch source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitch/Twitch.yaml -o ./Twitch/twitch.yaml
          rm -fr ./Twitch/twitch.yamle

          echo "Downloading Speedtest source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Speedtest/Speedtest.yaml -o ./Speedtest/speedtest.yaml
          rm -fr ./Speedtest/speedtest.yamle

          echo "Downloading youtube source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml -o ./Youtube/youtube.yaml
          rm -fr ./Youtube/youtube.yamle

          echo "Downloading Spotify source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml -o ./Spotify/spotify.yaml
          rm -fr ./Spotify/spotify.yamle

          echo "Downloading terabox source list..."
          curl -s https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TeraBox/TeraBox.yaml -o ./Terabox/terabox.yaml
          rm -fr ./Terabox/terabox.yamle

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Successfully Updated Rule Config